// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 28/8/2025, 11:41:56 pm
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/mvlakshman129/Desktop/gitaUnlocked/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mvlakshman129/Desktop/gitaUnlocked/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mvlakshman129/Desktop/gitaUnlocked/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mvlakshman129/Desktop/gitaUnlocked/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mvlakshman129/Desktop/gitaUnlocked/plugins/**/*.{js,ts,mjs}","C:/Users/mvlakshman129/Desktop/gitaUnlocked/composables/**/*.{js,ts,mjs}","C:/Users/mvlakshman129/Desktop/gitaUnlocked/utils/**/*.{js,ts,mjs}","C:/Users/mvlakshman129/Desktop/gitaUnlocked/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mvlakshman129/Desktop/gitaUnlocked/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mvlakshman129/Desktop/gitaUnlocked/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;