// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/30/2025, 2:01:04 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/apple/Desktop/gitaUnlocked/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Desktop/gitaUnlocked/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Desktop/gitaUnlocked/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Desktop/gitaUnlocked/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Desktop/gitaUnlocked/plugins/**/*.{js,ts,mjs}","/Users/apple/Desktop/gitaUnlocked/composables/**/*.{js,ts,mjs}","/Users/apple/Desktop/gitaUnlocked/utils/**/*.{js,ts,mjs}","/Users/apple/Desktop/gitaUnlocked/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Desktop/gitaUnlocked/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/apple/Desktop/gitaUnlocked/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;